### ISSUE TITLE
versions and signing

### ISSUE THREAD

**Issue by IzzySoft** [odrevet/yt-dlp-kivy#12]
Just wondering: Your version numbers went down from v0.2.1 to v0.1.x, and the signing key has changed (v0.2.1 had hash `236717590bfccbd4d89f95e10a26e9d21cfd1aca77438f0552ff02168fd50bf6`, while the latest v0.1.1 has hash `0a829a0bdb80543c329d3c4e227497e8228fe4285df6607e805d79c972eab60f`). This is quite confusing, and I cannot find any explanation. As updates are not possible anyway (due to the changed signing key), is the v0.2.x app supposed to be replaced by the current v0.1.x? The higher `versionCode` suggests as much.

A little clarification would be much appreciated :wink: 

One more point, if replacement was intended: APK size now is > 30 MB, which is the size limit for my repo (where [your app is listed](https://apt.izzysoft.de/fdroid/index/apk/fr.odrevet.youtube_dl_kivy.youtube_dl_kivy) – but updates were not applied due to the above reasons). Could you then please provide per-ABI builds and let me know which one you'd like to have included with the repo?

Thanks in advance!

**Comment by odrevet** [comment]
I have reset the version number to 0.1.0 because the project switched from youtube-dl to yt-dlp, felt like a new start for the app. If this is not convenient I can delete the 0.1.0 and version the next release to 0.3.0
  
I will try to build per abi

**Comment by IzzySoft** [comment]
Hi @odrevet, changing the versionName does not result in a different key hash, you must have chenged the signing key too – which is a bad idea as it not only makes updates impossible, but also raises the question if it was "really you". The signing key is a security feature, so no "imposter" can place an APK in your name. So may I ask for some background on that?

Decreasing `versionName` looks weird but has no real consequences (apart from maybe my updater no longer catching updates unless I adjust that manually here, which can be done easily) as long as you never decrease `versionCode` (which you really shouldn't and luckily haven't). But updates are rejected if the signing key has changed.

**Comment by IzzySoft** [comment]
So no explanation for the "broken key"? Sad. I've disabled updates now for your app in my repo (folks could not update to any new version anyway) and will have to remove it if we cannot solve this issue. For some background, see [How to keep your key safe and what measures to take for the event of loss?](https://f-droid.org/2023/09/03/reproducible-builds-signing-keys-and-binary-repos.html#lessons-learned-2-how-to-keep-your-key-safe-and-what-measures-to-take-for-the-event-of-loss)

**Comment by odrevet** [comment]
Solved with current release

**Comment by odrevet** [comment]
My mistake, I previously release the apk signed with the test keystore (I do am the original owner of the app)
Until I figure how to split per abi with buildozer I will only target arm64-v8a
The current release v0.3.1 should be good to go

**Comment by IzzySoft** [comment]
> I do am the original owner of the app

The certificate used to sign the latest APK confirms – thanks! :smiley:

> Until I figure how to split per abi with buildozer I will only target arm64-v8a

That's totally fine for my repo. I just added the now confirmed new APK (which will show up in my repo with the next sync around 6 pm UTC).

> The current release v0.3.1 should be good to go

Mostly. You forgot to adjust `versionName`, which currently is "0.3.0" and thus does not match the tag name (0.3.1) :see_no_evil: As that means my updater would unnecessarily pull that APK over and again, I've set it to check only once a month (instead of daily). If you let me know once that matches again, I can set it back to daily checks. Thanks!

**Comment by IzzySoft** [comment]
Just to verify: the `versionName` seems to be fixed now as well, as v0.3.2 in my repo identifies as such? I only wonder as `buildozer.spec` still says [`0.3.1`](https://github.com/odrevet/yt-dlp-kivy/blob/master/buildozer.spec#L15). But if you confirm, I'd close the issue on my end – and here, re-enabling daily update checks :smiley:

**Comment by odrevet** [comment]
I don't know. I released a new version just to be sure
